colorScheme = "ocean"
defaultAppearance = "dark"
mainSections = ["logbook", "riff-library", "the-portal", "commonplace", "the-studio"]

# Enable search
enableSearch = true

[homepage]
  layout = "custom"
  showRecent = true
  showRecentItems = 8
  cardView = true
  cardViewScreenWidth = false

[header]
  layout = "basic"

[article]
  showWordCount = false
  showReadingTime = false

[list]
  cardView = true
  groupByYear = false
