# Default theme configuration

theme = "blowfish"

[params]
  title = "My Website"
  description = "A simple website template."
  author = "John Doe"

[menu.main]
  [[menu.main.items]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main.items]]
    name = "About"
    url = "/about/"
    weight = 2
